ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    map_frame: map
    odom_frame: base_link
    base_link_frame: base_link
    world_frame: map

    # imu0: /imu
    # imu0_config: [false, false, false,
    #               true,  true,  true,
    #               false, false, false,
    #               false, false, false,
    #               true,  true,  true]
    # imu0_differential: false
    # imu0_remove_gravitational_acceleration: true

    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   true,  true,  false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 5
    odom0_differential: false

    use_control: false
    publish_tf: true
